# uncomment the line below and change the compiler flags if you need to (use at least c++11 on the server)
CXXFLAGS = -std=c++11 

all: 
	g++ RuntimeTestMain.cpp $(CXXFLAGS) -o Run
	g++ CDABreakMain.cpp $(CXXFLAGS) -o Break
run:
	g++ RuntimeTestMain.cpp $(CXXFLAGS) -o Run
break:
	g++ CDABreakMain.cpp $(CXXFLAGS) -o Break
